### ISSUE TITLE
error running quickstart

### ISSUE THREAD

**Issue by yayitswei** [mrhornsby/zookeeper#1]
First of all, thanks for creating this image with the latest zookeeper branch!

I'm getting the following error when starting the quickstart with:

`docker run --volume=/var/opt/zookeeper -p 2181:2181 mrhornsby/zookeeper:latest`

```
2017-09-23 00:54:13,130 [myid:1] - WARN  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):QuorumPeer@1127] - Unexpected exception
java.net.SocketException: Unresolved address
	at java.net.ServerSocket.bind(ServerSocket.java:368)
	at java.net.ServerSocket.bind(ServerSocket.java:329)
	at org.apache.zookeeper.server.quorum.Leader.<init>(Leader.java:229)
	at org.apache.zookeeper.server.quorum.QuorumPeer.makeLeader(QuorumPeer.java:920)
	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1123)
```

Am I missing something?

**Comment by mrhornsby** [comment]
Hi Wei,

It looks like something has changed in newer versions of Docker - the container is struggling to resolve it's own name (it is expected to be **zk-1**). You can use the following command (note the **-h zk-1**):

```
docker run --volume=/var/opt/zookeeper -h zk-1 -p 2181:2181 mrhornsby/zookeeper:latest
```

That should work for you. I'll update the documentation. I haven't checked if this also affects running the docker-compose cluster - will try that later today.

**Comment by mrhornsby** [comment]
I checked the docker-compose - that is working fine as each container has a specified name. I've updated the readme. Thanks for reporting the problem, let me know if you have any other issues! 👍

**Comment by yayitswei** [comment]
Thanks!
